name: Teams
version: 1.1.1
main: me.ITGuy12.teams.Main
description: Adds PVP teams to the game. The team members have friendly fire disabled.
author: ITGuy12
commands:
  team:
    description: Main command for teams. Invite a player to a team, leave your team, etc.
    aliases: [team]