name: Teams
version: 1.0.0
main: me.ITGuy12.teams
description: Adds PVP teams to the game. The team members have friendly fire disabled.
author: ITGuy12
commands:
  team:
    description: Main command for teams. Invite a player to a team, leave your team, etc.
    aliases: [team]